version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./config/jwt:/var/www/config/jwt # JWT keys
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/symfony_master?serverVersion=8&charset=utf8mb4"
      AWS_S3_BUCKET: "cw-recruitment-tests"
      AWS_S3_REGION: "eu-west-1"
      AWS_KEY: "AKIA4TBHNXI5MRYR4B7P"
      AWS_SECRET: "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"
      JWT_SECRET_KEY: "/var/www/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "/var/www/config/jwt/public.pem"
      JWT_PASSPHRASE: "password"
      MAILER_FROM_EMAIL: "newsletter@cobbleweb.co.uk"
      MAILER_DSN: "null://null"
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
    depends_on:
      - database

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - "8000:80"
    depends_on:
      - backend

  database:
    image: mysql:5.7
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: symfony_master
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
        REACT_APP_API_URL: "http://localhost:8000/api"
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"

volumes:
  mysqldata:
